#!/bin/bash

# Author: slowpoke <proxypoke at lavabit dot com>
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
#
# A pre-commit hook for go projects. In addition to the standard
# checks from the sample hook, it builds the project with go build,
# runs the tests (if any), formats the source code with go fmt, and
# finally go vet to make sure only correct and good code is committed.

# If there are no go files, it makes no sense to run the other commands
# (and indeed, go build would fail). This is undesirable.
if [ -z "$(ls | grep '\.go$')" ]
then
    echo "No '.go' files found to run pre-commit hook on"
    exit 0
fi

go fmt ./... >/dev/null 2>&1
if [ $? -ne 0 ]
then
    echo "Failed to run go fmt. This shouldn't happen. Please"
    echo "check the output of the command to see what's wrong"
    echo "or run commit with --no-verify if you know what you"
    echo "are doing."

    exit 1
fi

go vet ./... >/dev/null 2>&1
if [ $? -ne 0 ]
then
    echo "go vet has detected potential issues in your project."
    echo "Please check its output or run commit with --no-verify"
    echo "if you know what you are doing."
    exit 1
fi
